"use client"; import Link from "next/link"; import { ArrowLeft, ArrowRight, Warehouse, LayoutList, Users, Clock, Ship, TrendingUp, Shield, Zap } from "lucide-react";
export default function WarehouseOpsPage() {
  return (<main className="min-h-screen bg-white text-[#1a1a2e]"><header className="sticky top-0 z-40 border-b border-[#e5e7eb]/60 bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link href="/" className="flex items-center gap-2"><div className="grid h-7 w-7 place-items-center rounded-md bg-[#1a1a2e]"><div className="h-3 w-3 rounded-sm bg-[#93c5fd]" style={{transform:"rotate(45deg)"}} /></div><span className="text-lg font-semibold">Lanework</span></Link><Link href="/register" className="rounded-full bg-[#1a1a2e] px-4 py-2 text-sm font-medium text-white hover:bg-[#1a1a2e]/90">Start Free Trial <ArrowRight className="inline h-3.5 w-3.5 ml-1" /></Link></div></header>
  <div className="mx-auto max-w-4xl px-6 py-16"><Link href="/#agents" className="inline-flex items-center gap-1 text-sm text-[#1a1a2e]/60 hover:text-[#1a1a2e] mb-8"><ArrowLeft className="h-4 w-4" /> All agents</Link>
  <div className="flex items-center gap-4 mb-8"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#1a1a2e] text-white"><Warehouse className="h-8 w-8" /></div><div><h1 className="text-4xl font-semibold">Warehouse Operations Agent</h1><p className="mt-1 text-[#1a1a2e]/60">Smarter picks. Faster docks. Less chaos.</p></div></div>
  <section className="max-w-none"><h2 className="text-2xl font-semibold mt-10">What it does</h2><p className="text-[#1a1a2e]/70 leading-relaxed">The Warehouse Operations agent optimizes every movement inside your DC — from pick path sequencing to dock door scheduling. It auto-assigns tasks to warehouse associates based on priority, proximity, and skill, and rebalances workloads in real time when a truck is running late or a picker is overloaded.</p>
  <h2 className="text-2xl font-semibold mt-10">Why you need it</h2><div className="grid gap-4 md:grid-cols-2 mt-4">
    {[{Icon:LayoutList,title:"Dynamic pick paths",desc:"Calculates the shortest walk path for each pick list, updated in real-time as inventory locations change. Reduces walk time by 20-30%."},{Icon:Ship,title:"Dock door scheduling",desc:"Auto-assigns arriving trucks to optimal docks based on load type, unloading time, and warehouse congestion. Eliminates dock conflicts."},{Icon:Users,title:"Task auto-assignment",desc:"Assigns pick/pack/ship tasks to the right associate based on current location, workload, and skill level. No more manual dispatch."},{Icon:Clock,title:"Cross-docking orchestration",desc:"Identifies cross-dock opportunities in real time. When inbound matches outbound, the agent triggers direct transfer — bypassing putaway."}].map(({Icon,title,desc})=>(<div key={title} className="flex gap-3 p-4 rounded-xl border border-[#e5e7eb]"><Icon className="h-5 w-5 text-[#1a1a2e] mt-0.5 flex-shrink-0" /><div><div className="font-medium text-sm">{title}</div><div className="text-xs text-[#1a1a2e]/60 mt-1">{desc}</div></div></div>))}
  </div>
  <h2 className="text-2xl font-semibold mt-10">How it works</h2><div className="space-y-4 mt-4">
    {[{step:"1",title:"Map your warehouse layout",desc:"Upload your floor plan or let the agent learn from historical pick data. It builds a digital twin of your DC."},{step:"2",title:"Connect your WMS",desc:"Plug into your existing WMS to pull orders, inventory locations, and associate schedules. The agent syncs every 60 seconds."},{step:"3",title:"Agent optimizes in real time",desc:"As orders come in, the agent sequences picks, assigns docks, and routes associates. It adapts to delays, priority changes, and call-outs."},{step:"4",title:"Associates get mobile instructions",desc:"Pick lists, dock assignments, and task updates appear on handheld scanners or mobile devices. No paper, no radio, no confusion."}].map(({step,title,desc})=>(<div key={step} className="flex gap-4 p-5 rounded-xl border border-[#e5e7eb] bg-white"><div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-[#1a1a2e] text-white text-sm font-semibold">{step}</div><div><div className="font-medium">{title}</div><div className="text-sm text-[#1a1a2e]/60 mt-1">{desc}</div></div></div>))}
  </div>
  <h2 className="text-2xl font-semibold mt-10">Trust &amp; control</h2><div className="flex items-start gap-4 p-5 rounded-xl bg-[#fafafa] border border-[#e5e7eb] mt-4"><Shield className="h-5 w-5 text-[#1a1a2e] mt-0.5 flex-shrink-0" /><div className="text-sm text-[#1a1a2e]/70 leading-relaxed"><span className="font-medium text-[#1a1a2e]">Task assignments are auto-executed. Dock changes are proposed.</span> The agent can assign picks and putaways autonomously. Dock reassignments and cross-dock decisions are proposed for supervisor approval with reasoning.</div></div>
  <div className="mt-12 flex gap-3"><Link href="/register" className="inline-flex items-center gap-2 rounded-full bg-[#1a1a2e] px-6 py-3 text-sm font-medium text-white hover:bg-[#1a1a2e]/90">Start Free Trial <ArrowRight className="h-4 w-4" /></Link><Link href="/#agents" className="inline-flex items-center gap-2 rounded-full border border-[#1a1a2e]/20 px-6 py-3 text-sm font-medium text-[#1a1a2e] hover:bg-[#1a1a2e]/5">Explore other agents <ArrowRight className="h-4 w-4" /></Link></div></section></div></main>);
}