"use client";
import Link from "next/link"; import { ArrowLeft, ArrowRight, Route, MapPin, Clock, TrendingDown, AlertTriangle, Zap, Shield, Truck } from "lucide-react";
import { AgentLiveActivity } from "@/components/ui/agent-live-activity";
export default function RouteOptimizationPage() {
  return (<main className="min-h-screen bg-white text-[#1a1a2e]"><header className="sticky top-0 z-40 border-b border-[#e5e7eb]/60 bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link href="/" className="flex items-center gap-2"><div className="grid h-7 w-7 place-items-center rounded-md bg-[#1a1a2e]"><div className="h-3 w-3 rounded-sm bg-[#93c5fd]" style={{transform:"rotate(45deg)"}} /></div><span className="text-lg font-semibold">Lanework</span></Link><Link href="/register" className="rounded-full bg-[#1a1a2e] px-4 py-2 text-sm font-medium text-white hover:bg-[#1a1a2e]/90">Start Free Trial <ArrowRight className="inline h-3.5 w-3.5 ml-1" /></Link></div></header>
  <div className="mx-auto max-w-4xl px-6 py-16"><Link href="/#agents" className="inline-flex items-center gap-1 text-sm text-[#1a1a2e]/60 hover:text-[#1a1a2e] mb-8"><ArrowLeft className="h-4 w-4" /> All agents</Link>
  <div className="flex items-center gap-4 mb-8"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#1a1a2e] text-white"><Route className="h-8 w-8" /></div><div><h1 className="text-4xl font-semibold">Route Optimization Agent</h1><p className="mt-1 text-[#1a1a2e]/60">Every route, recalculated every minute.</p></div></div>
  <section className="max-w-none"><h2 className="text-2xl font-semibold mt-10">What it does</h2><p className="text-[#1a1a2e]/70 leading-relaxed">The Route Optimization agent continuously recalculates delivery routes based on live traffic, weather, road closures, new orders, and priority changes. It handles multi-stop routes, time-window constraints, hazmat restrictions, and vehicle capacity limits — all in real time.</p>
  <h2 className="text-2xl font-semibold mt-10">Why you need it</h2><div className="grid gap-4 md:grid-cols-2 mt-4">
    {[{Icon:MapPin,title:"Real-time rerouting",desc:"Detects road closures, accidents, and congestion within minutes. Automatically suggests alternate routes with cost/time tradeoffs."},{Icon:Clock,title:"Time-window compliance",desc:"Ensures deliveries arrive within promised windows. Reprioritizes stops when a window is at risk of being missed."},{Icon:TrendingDown,title:"Fuel cost reduction",desc:"Optimizes for minimum fuel consumption. Routes that save 12-18% on fuel compared to standard GPS navigation."},{Icon:AlertTriangle,title:"Constraint-aware planning",desc:"Respects vehicle height/weight limits, hazmat restrictions, driver hours, and toll preferences automatically."}].map(({Icon,title,desc})=>(<div key={title} className="flex gap-3 p-4 rounded-xl border border-[#e5e7eb]"><Icon className="h-5 w-5 text-[#1a1a2e] mt-0.5 flex-shrink-0" /><div><div className="font-medium text-sm">{title}</div><div className="text-xs text-[#1a1a2e]/60 mt-1">{desc}</div></div></div>))}
  </div>
  <h2 className="text-2xl font-semibold mt-10">How it works</h2><div className="space-y-4 mt-4">
    {[{step:"1",title:"Upload orders or connect your TMS",desc:"Import a CSV of today's deliveries or plug into your TMS. The agent pulls orders, addresses, time windows, and vehicle assignments."},{step:"2",title:"Agent generates initial routes",desc:"Within 30 seconds, the agent produces optimized routes considering distance, time windows, vehicle capacity, and driver shifts."},{step:"3",title:"Continuous monitoring & rerouting",desc:"Every minute, the agent checks for disruptions — traffic, weather, new priority orders — and recalculates affected routes."},{step:"4",title:"Drivers get turn-by-turn updates",desc:"Route changes are pushed to driver apps or WhatsApp. No need to call dispatch — the new route just appears."}].map(({step,title,desc})=>(<div key={step} className="flex gap-4 p-5 rounded-xl border border-[#e5e7eb] bg-white"><div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-[#1a1a2e] text-white text-sm font-semibold">{step}</div><div><div className="font-medium">{title}</div><div className="text-sm text-[#1a1a2e]/60 mt-1">{desc}</div></div></div>))}
  </div>
  <AgentLiveActivity agentId="route-optimization" />
  <h2 className="text-2xl font-semibold mt-10">Trust &amp; control</h2><div className="flex items-start gap-4 p-5 rounded-xl bg-[#fafafa] border border-[#e5e7eb] mt-4"><Shield className="h-5 w-5 text-[#1a1a2e] mt-0.5 flex-shrink-0" /><div className="text-sm text-[#1a1a2e]/70 leading-relaxed"><span className="font-medium text-[#1a1a2e]">Reroutes under 30 minutes are auto-applied.</span> Major deviations (30+ minutes, or cost impact above threshold) are proposed for your approval with a clear before/after comparison. You always have a one-click undo.</div></div>
  <div className="mt-12 flex gap-3"><Link href="/register" className="inline-flex items-center gap-2 rounded-full bg-[#1a1a2e] px-6 py-3 text-sm font-medium text-white hover:bg-[#1a1a2e]/90">Start Free Trial <ArrowRight className="h-4 w-4" /></Link><Link href="/#agents" className="inline-flex items-center gap-2 rounded-full border border-[#1a1a2e]/20 px-6 py-3 text-sm font-medium text-[#1a1a2e] hover:bg-[#1a1a2e]/5">Explore other agents <ArrowRight className="h-4 w-4" /></Link></div></section></div></main>);
}
