"use client"; import Link from "next/link"; import { ArrowLeft, ArrowRight, Users, Wrench, Clock, Gauge, AlertTriangle, FileText, Shield, Truck } from "lucide-react";
import { AgentLiveActivity } from "@/components/ui/agent-live-activity";
export default function FleetManagementPage() {
  return (<main className="min-h-screen bg-white text-[#1a1a2e]"><header className="sticky top-0 z-40 border-b border-[#e5e7eb]/60 bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link href="/" className="flex items-center gap-2"><div className="grid h-7 w-7 place-items-center rounded-md bg-[#1a1a2e]"><div className="h-3 w-3 rounded-sm bg-[#93c5fd]" style={{transform:"rotate(45deg)"}} /></div><span className="text-lg font-semibold">Lanework</span></Link><Link href="/register" className="rounded-full bg-[#1a1a2e] px-4 py-2 text-sm font-medium text-white hover:bg-[#1a1a2e]/90">Start Free <ArrowRight className="inline h-3.5 w-3.5 ml-1" /></Link></div></header>
  <div className="mx-auto max-w-4xl px-6 py-16"><Link href="/#agents" className="inline-flex items-center gap-1 text-sm text-[#1a1a2e]/60 hover:text-[#1a1a2e] mb-8"><ArrowLeft className="h-4 w-4" /> All agents</Link>
  <div className="flex items-center gap-4 mb-8"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#1a1a2e] text-white"><Users className="h-8 w-8" /></div><div><h1 className="text-4xl font-semibold">Fleet &amp; Driver Management Agent</h1><p className="mt-1 text-[#1a1a2e]/60">Vehicles that never break down. Drivers that never violate hours.</p></div></div>
  <section className="max-w-none"><h2 className="text-2xl font-semibold mt-10">What it does</h2><p className="text-[#1a1a2e]/70 leading-relaxed">The Fleet Management agent tracks every vehicle and driver in your fleet. It schedules preventive maintenance before breakdowns happen, monitors driver hours for legal compliance, integrates with telematics for real-time location and fuel data, and auto-generates incident reports when something goes wrong.</p>
  <h2 className="text-2xl font-semibold mt-10">Why you need it</h2><div className="grid gap-4 md:grid-cols-2 mt-4">
    {[{Icon:Wrench,title:"Preventive maintenance",desc:"Schedules service based on actual mileage, engine hours, and manufacturer intervals. Alerts you 2 weeks before due date."},{Icon:Clock,title:"Driver hours compliance",desc:"Tracks Hours of Service (HOS) in real time. Predicts violations before they happen and suggests driver swaps."},{Icon:Gauge,title:"Telematics integration",desc:"Pulls live GPS, fuel consumption, speed, and engine diagnostics from Samsara, Fleetio, or your existing telematics provider."},{Icon:FileText,title:"Incident auto-reporting",desc:"Detects harsh braking, speeding, or accidents from telematics. Auto-generates incident reports with timestamps and location data."}].map(({Icon,title,desc})=>(<div key={title} className="flex gap-3 p-4 rounded-xl border border-[#e5e7eb]"><Icon className="h-5 w-5 text-[#1a1a2e] mt-0.5 flex-shrink-0" /><div><div className="font-medium text-sm">{title}</div><div className="text-xs text-[#1a1a2e]/60 mt-1">{desc}</div></div></div>))}
  </div>
  <h2 className="text-2xl font-semibold mt-10">How it works</h2><div className="space-y-4 mt-4">
    {[{step:"1",title:"Connect your fleet data",desc:"Link your telematics provider, upload driver records, and import vehicle maintenance history. The agent syncs every 15 minutes."},{step:"2",title:"Agent monitors continuously",desc:"Tracks vehicle location, mileage, fuel levels, engine fault codes, and driver hours. Flags anomalies and predicts maintenance needs."},{step:"3",title:"Alerts and recommendations",desc:"When maintenance is due, a driver is approaching HOS limits, or a vehicle has a fault code — the agent alerts the right person with a clear recommendation."},{step:"4",title:"Reports and compliance",desc:"Auto-generates monthly maintenance reports, driver hour summaries, and incident logs. Ready for audits and insurance renewals."}].map(({step,title,desc})=>(<div key={step} className="flex gap-4 p-5 rounded-xl border border-[#e5e7eb] bg-white"><div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-[#1a1a2e] text-white text-sm font-semibold">{step}</div><div><div className="font-medium">{title}</div><div className="text-sm text-[#1a1a2e]/60 mt-1">{desc}</div></div></div>))}
  </div>
  <AgentLiveActivity agentId="fleet-management" />
  <h2 className="text-2xl font-semibold mt-10">Trust &amp; control</h2><div className="flex items-start gap-4 p-5 rounded-xl bg-[#fafafa] border border-[#e5e7eb] mt-4"><Shield className="h-5 w-5 text-[#1a1a2e] mt-0.5 flex-shrink-0" /><div className="text-sm text-[#1a1a2e]/70 leading-relaxed"><span className="font-medium text-[#1a1a2e]">Maintenance alerts are auto-sent. Driver swaps are proposed.</span> The agent can auto-schedule maintenance and notify drivers. Driver reassignments and incident escalations are proposed for fleet manager approval.</div></div>
  <div className="mt-12 flex gap-3"><Link href="/register" className="inline-flex items-center gap-2 rounded-full bg-[#1a1a2e] px-6 py-3 text-sm font-medium text-white hover:bg-[#1a1a2e]/90">Start Free <ArrowRight className="h-4 w-4" /></Link><Link href="/#agents" className="inline-flex items-center gap-2 rounded-full border border-[#1a1a2e]/20 px-6 py-3 text-sm font-medium text-[#1a1a2e] hover:bg-[#1a1a2e]/5">Explore other agents <ArrowRight className="h-4 w-4" /></Link></div></section></div></main>);
}