"use client";
import Link from "next/link"; import { ArrowRight, Plug, Sliders, Play, ShieldCheck, ArrowLeft } from "lucide-react";
export default function HowItWorksPage() {
  return (<main className="min-h-screen bg-white text-[#1a1a2e]"><header className="sticky top-0 z-40 border-b border-[#e5e7eb]/60 bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link href="/" className="flex items-center gap-2"><div className="grid h-7 w-7 place-items-center rounded-md bg-[#1a1a2e]"><div className="h-3 w-3 rounded-sm bg-[#93c5fd]" style={{transform:"rotate(45deg)"}} /></div><span className="text-lg font-semibold">Lanework</span></Link><Link href="/register" className="rounded-full bg-[#1a1a2e] px-4 py-2 text-sm font-medium text-white hover:bg-[#1a1a2e]/90">Start Free Trial <ArrowRight className="inline h-3.5 w-3.5 ml-1" /></Link></div></header>
  <div className="mx-auto max-w-4xl px-6 py-16"><h1 className="text-5xl font-semibold">How Lanework Works</h1><p className="mt-4 text-lg text-[#1a1a2e]/60">Three steps. No rip-and-replace. Your existing systems stay exactly where they are.</p>
  <div className="grid gap-8 md:grid-cols-3 mt-12">
    {[{Icon:Plug,n:"01",title:"Connect",desc:"Plug into your existing TMS, WMS, ERP, and carrier accounts. Lanework reads from your systems — it doesn't replace them. One-time setup, instant sync."},{Icon:Sliders,n:"02",title:"Configure",desc:"Choose which decisions each agent can make on its own, and which ones come to your team. Set per-agent trust levels and spending thresholds."},{Icon:Play,n:"03",title:"Operate",desc:"Agents start working immediately — watching for delays, optimizing routes, reordering stock, communicating with customers. You watch the dashboard."}].map(s=>(<div key={s.n} className="rounded-2xl border border-[#e5e7eb] bg-white p-8"><div className="flex items-center justify-between"><span className="font-serif text-3xl text-[#1a1a2e]/25">{s.n}</span><s.Icon className="h-5 w-5 text-[#1a1a2e]/60" /></div><h3 className="mt-6 text-2xl font-semibold">{s.title}</h3><p className="mt-3 text-[#1a1a2e]/65 leading-relaxed">{s.desc}</p></div>))}
  </div>
  <div className="mt-16 p-8 rounded-2xl border border-[#e5e7eb] bg-[#fafafa]"><h2 className="text-2xl font-semibold">Under the hood</h2><div className="grid gap-4 md:grid-cols-2 mt-6">{[{title:"Agent Autonomy Levels",desc:"Propose only → Agent suggests, you approve. Auto-execute low-risk → Runs within thresholds. Fully autonomous → Independent operation with guardrails."},{title:"Real-Time Monitoring",desc:"Every agent action is streamed to your dashboard. You see what happened, why it happened, and when — in plain English."},{title:"Audit Trail",desc:"Every decision — auto or manual — is logged with a full reasoning trace. Searchable, exportable, audit-ready."},{title:"Tenant Isolation",desc:"Your data never mixes with other customers. Each workspace runs in its own isolated environment."}].map(({title,desc})=>(<div key={title} className="flex gap-3"><ShieldCheck className="h-5 w-5 text-[#1a1a2e] mt-0.5 flex-shrink-0" /><div><div className="font-medium text-sm">{title}</div><div className="text-xs text-[#1a1a2e]/60 mt-1">{desc}</div></div></div>))}</div></div></div></main>);
}
