"use client";
import Link from "next/link"; import { ArrowRight, Check, X, HelpCircle } from "lucide-react";
const tiers = [{name:"Starter",price:"₹24,999",per:"/mo",desc:"3 agents of your choice",quota:"5,000 tracked shipments",feats:["3 AI agents","5,000 shipments/mo","CSV import","Email support","14-day free trial"],cta:"Start Free Trial",href:"/register"},{name:"Growth",price:"₹83,299",per:"/mo",desc:"All 6 agents",quota:"25,000 tracked shipments",feats:["All 6 AI agents","25,000 shipments/mo","WhatsApp + TMS integrations","Priority support","API access","Custom trust levels"],cta:"Start Free Trial",href:"/register",featured:!0},{name:"Scale",price:"₹2,49,999",per:"/mo",desc:"All 6 agents",quota:"50,000 tracked shipments",feats:["All 6 AI agents","50,000 shipments/mo","All integrations","Dedicated support","SSO","Custom SLAs","Unlimited API access"],cta:"Start Free Trial",href:"/register"},{name:"Enterprise",price:"Custom",per:"",desc:"Unlimited everything",quota:"Volume pricing",feats:["All Scale features","Unlimited shipments","On-premise deployment option","Dedicated account manager","Custom AI model training","24/7 phone support"],cta:"Talk to Sales",href:"/register"}];
export default function PricingPage() {
  return (<main className="min-h-screen bg-white text-[#1a1a2e]"><header className="sticky top-0 z-40 border-b border-[#e5e7eb]/60 bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link href="/" className="flex items-center gap-2"><div className="grid h-7 w-7 place-items-center rounded-md bg-[#1a1a2e]"><div className="h-3 w-3 rounded-sm bg-[#93c5fd]" style={{transform:"rotate(45deg)"}} /></div><span className="text-lg font-semibold">Lanework</span></Link><Link href="/register" className="rounded-full bg-[#1a1a2e] px-4 py-2 text-sm font-medium text-white hover:bg-[#1a1a2e]/90">Start Free Trial <ArrowRight className="inline h-3.5 w-3.5 ml-1" /></Link></div></header>
  <div className="mx-auto max-w-6xl px-6 py-16 text-center"><h1 className="text-5xl font-semibold">Simple pricing that <em className="italic">scales with you.</em></h1><p className="mt-4 text-lg text-[#1a1a2e]/60 max-w-2xl mx-auto">Every plan includes a usage allowance. Pay only for what you go over. 14-day free trial, no credit card required.</p>
  <div className="grid gap-6 md:grid-cols-4 mt-12 text-left">
    {tiers.map(t=>(<div key={t.name} className={`flex flex-col rounded-2xl border p-7 ${t.featured?"border-[#1a1a2e] bg-[#1a1a2e] text-white":"border-[#e5e7eb] bg-white text-[#1a1a2e]"}`}><div className={t.featured?"text-sm text-white/70":"text-sm text-[#1a1a2e]/60"}>{t.name}</div><div className="mt-3 flex items-baseline gap-1"><span className="font-serif text-4xl">{t.price}</span><span className={t.featured?"text-white/60":"text-[#1a1a2e]/50"}>{t.per}</span></div><p className={`mt-4 text-sm ${t.featured?"text-white/80":"text-[#1a1a2e]/70"}`}>{t.desc}</p><p className={`mt-2 text-xs ${t.featured?"text-white/60":"text-[#1a1a2e]/55"}`}>{t.quota}</p><ul className="mt-6 space-y-2.5 flex-1">{t.feats.map(f=>(<li key={f} className="flex items-start gap-2 text-xs"><Check className={`h-3.5 w-3.5 mt-0.5 flex-shrink-0 ${t.featured?"text-emerald-400":"text-emerald-600"}`} />{f}</li>))}</ul><Link href={t.href} className={`mt-8 inline-flex items-center justify-center rounded-full px-4 py-2.5 text-sm font-medium ${t.featured?"bg-white text-[#1a1a2e] hover:bg-white/90":"bg-[#1a1a2e] text-white hover:bg-[#1a1a2e]/90"}`}>{t.cta}</Link></div>))}
  </div>
  <div className="mt-16 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 text-left max-w-4xl mx-auto">
    {[{q:"Can I change plans?",a:"Yes, upgrade or downgrade anytime."},{q:"Is there a contract?",a:"Month-to-month. Cancel anytime."},{q:"What counts as usage?",a:"Tracked shipments per billing month."},{q:"Need a custom plan?",a:"Contact us for volume pricing."}].map(f=>(<div key={f.q} className="p-4 rounded-xl border border-[#e5e7eb]"><HelpCircle className="h-4 w-4 text-[#1a1a2e]/40 mb-2" /><div className="text-sm font-medium">{f.q}</div><div className="text-xs text-[#1a1a2e]/60 mt-1">{f.a}</div></div>))}
  </div></div></main>);
}
