"use client"; import Link from "next/link"; import { ArrowLeft, ArrowRight, MessageSquare, Globe, Smile, Send, Phone, Clock, Shield, Users } from "lucide-react";
export default function CustomerCommunicationPage() {
  return (<main className="min-h-screen bg-white text-[#1a1a2e]"><header className="sticky top-0 z-40 border-b border-[#e5e7eb]/60 bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link href="/" className="flex items-center gap-2"><div className="grid h-7 w-7 place-items-center rounded-md bg-[#1a1a2e]"><div className="h-3 w-3 rounded-sm bg-[#93c5fd]" style={{transform:"rotate(45deg)"}} /></div><span className="text-lg font-semibold">Lanework</span></Link><Link href="/register" className="rounded-full bg-[#1a1a2e] px-4 py-2 text-sm font-medium text-white hover:bg-[#1a1a2e]/90">Start Free Trial <ArrowRight className="inline h-3.5 w-3.5 ml-1" /></Link></div></header>
  <div className="mx-auto max-w-4xl px-6 py-16"><Link href="/#agents" className="inline-flex items-center gap-1 text-sm text-[#1a1a2e]/60 hover:text-[#1a1a2e] mb-8"><ArrowLeft className="h-4 w-4" /> All agents</Link>
  <div className="flex items-center gap-4 mb-8"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#1a1a2e] text-white"><MessageSquare className="h-8 w-8" /></div><div><h1 className="text-4xl font-semibold">Customer Communication Agent</h1><p className="mt-1 text-[#1a1a2e]/60">Your customers get answers. Your team gets their time back.</p></div></div>
  <section className="max-w-none"><h2 className="text-2xl font-semibold mt-10">What it does</h2><p className="text-[#1a1a2e]/70 leading-relaxed">The Customer Communication agent handles the most common — and most time-consuming — customer interaction: &ldquo;Where&rsquo;s my order?&rdquo; It auto-replies to tracking inquiries across Email, SMS, and WhatsApp, routes angry customers to human agents, schedules delivery windows, and collects feedback — all without a single click from your team.</p>
  <h2 className="text-2xl font-semibold mt-10">Why you need it</h2><div className="grid gap-4 md:grid-cols-2 mt-4">
    {[{Icon:Send,title:"Automated tracking replies",desc:"Handles 80% of WISMO (Where Is My Order) inquiries automatically. Replies include live tracking link, ETA, and current status."},{Icon:Smile,title:"Sentiment-based routing",desc:"Detects angry or urgent messages and escalates to a human agent immediately. Happy inquiries stay with the AI."},{Icon:Globe,title:"Multi-channel support",desc:"Works across Email, SMS, WhatsApp, and in-app chat. One agent, one conversation thread, any channel."},{Icon:Phone,title:"Delivery window scheduling",desc:"Proactively messages customers with delivery windows. Customers can confirm, reschedule, or add delivery instructions by replying."}].map(({Icon,title,desc})=>(<div key={title} className="flex gap-3 p-4 rounded-xl border border-[#e5e7eb]"><Icon className="h-5 w-5 text-[#1a1a2e] mt-0.5 flex-shrink-0" /><div><div className="font-medium text-sm">{title}</div><div className="text-xs text-[#1a1a2e]/60 mt-1">{desc}</div></div></div>))}
  </div>
  <h2 className="text-2xl font-semibold mt-10">How it works</h2><div className="space-y-4 mt-4">
    {[{step:"1",title:"Connect your communication channels",desc:"Link your WhatsApp Business API, email (Gmail/Outlook), and SMS provider. The agent monitors all channels in one inbox."},{step:"2",title:"Agent auto-responds to tracking queries",desc:"When a customer asks about their order, the agent pulls live tracking data and responds instantly — no human needed."},{step:"3",title:"Sentiment analysis triggers escalation",desc:"If the agent detects anger, urgency, or a complex issue, it routes the conversation to the right human agent with full context."},{step:"4",title:"Feedback loop closes the cycle",desc:"After delivery, the agent sends a satisfaction survey. Responses feed into carrier and service quality scoring."}].map(({step,title,desc})=>(<div key={step} className="flex gap-4 p-5 rounded-xl border border-[#e5e7eb] bg-white"><div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-[#1a1a2e] text-white text-sm font-semibold">{step}</div><div><div className="font-medium">{title}</div><div className="text-sm text-[#1a1a2e]/60 mt-1">{desc}</div></div></div>))}
  </div>
  <h2 className="text-2xl font-semibold mt-10">Trust &amp; control</h2><div className="flex items-start gap-4 p-5 rounded-xl bg-[#fafafa] border border-[#e5e7eb] mt-4"><Shield className="h-5 w-5 text-[#1a1a2e] mt-0.5 flex-shrink-0" /><div className="text-sm text-[#1a1a2e]/70 leading-relaxed"><span className="font-medium text-[#1a1a2e]">Tracking replies are fully automated. Anything else is reviewed.</span> The agent auto-replies to tracking inquiries. Rescheduling, complaints, and refund requests are always routed to a human. You can customize the rules per customer tier.</div></div>
  <div className="mt-12 flex gap-3"><Link href="/register" className="inline-flex items-center gap-2 rounded-full bg-[#1a1a2e] px-6 py-3 text-sm font-medium text-white hover:bg-[#1a1a2e]/90">Start Free Trial <ArrowRight className="h-4 w-4" /></Link><Link href="/#agents" className="inline-flex items-center gap-2 rounded-full border border-[#1a1a2e]/20 px-6 py-3 text-sm font-medium text-[#1a1a2e] hover:bg-[#1a1a2e]/5">Explore other agents <ArrowRight className="h-4 w-4" /></Link></div></section></div></main>);
}